name: Deploy static content to Pages

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6

      - name: install dependencies
        run: pip install --no-cache-ir -r dependencies.txt

      - name: Freeze Flask app
        run: |
          export FLASK_APP=app.py
          flask Freeze

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
